theme: minima

defaults:
  - scope:
      path: some-path
      layout: some_layout
    values:
      strip_title: true

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
